# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g1uE2ia_fo8oRTxBBs0k-S5kOaluMBun

Q.1
"""

N=[]
N.append("2")
N.append("4")
N.append("6")
N.append("8")
N.append("10")
N.append("12")
N.append("14")
N.append("16")
N.append("18")
N.append("20")
print(N)

"""Q.2"""

i=1 
while i<=10:
  print(i,end=" ")
  i=i+1

i=1 
while i<=10:
  print(i)
  i=i+1

"""Q.3"""

n=int(input("type a number "))
d = dict()

for i in range(1,n+1):
    d[i]=i*i

print(d)

"""Q.4"""

pos = {"x":0,"y":0}
num = int(input())

for _ in range (num):
    command =  input().split(" ")      # ACCEPT MOVEMENT COMMAND AND STORE AS A LIST
    if command[0] == "UP":             # EXTRACT DIRECTION AND COMPARE
        pos["y"] += int(command[1])    # INCREMENT/DECREMENT APPROPRIATE CO-ORDINATES
    if command[0] == "DOWN":
        pos["y"] -= int(command[1])
    if command[0] == "LEFT":
        pos["x"] -= int(command[1])
    if command[0] == "RIGHT":
        pos["x"] += int(command[1])

print(int(round((pos["x"]**2 + pos["y"]**2)**0.5)))